### ISSUE TITLE
Please include copyright from github.com/larrymyers/protoc-gen-twirp_typescript

### ISSUE THREAD

**Issue by larrymyers** [horizon-games/protoc-gen-twirp_ts#2]
I'm glad my twirp generator for typescript provided a base to work from, but please include the copyright from the project if you are going to use significant parts of the code, as specified by the MIT license.

See:

https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/minimal/twirp_common.go

compared with:

https://github.com/horizon-games/protoc-gen-twirp_ts/blob/master/twirp.go

**Comment by pkieltyka** [comment]
hey @larrymyers we have a line in that source file already referencing your project: https://github.com/horizon-games/protoc-gen-twirp_ts/blob/master/twirp.go#L5

but I've also included a new credits section in the README, https://github.com/horizon-games/protoc-gen-twirp_ts#credits
